name: deploy github pages
run-name: ${{ github.actor }} å¼€å§‹æ„å»ºå¹¶éƒ¨ç½²åˆ° github page ğŸš€
on:
  push:
    branches:
      - main
    tags:
      -*
jobs:
  build:
    name: build - æ„å»º
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout - è¿å‡ºæ–‡ä»¶
        uses: actions/checkout@v4.1.1
      - name: Setup Nodejs åˆå§‹åŒ–nodejs
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
      - name: Install Dependencies - å®‰è£…ä¾èµ–
        run: npm install
      - name: build - æ„å»º
        run: npm run build
      - name: mv - é‡å‘½å
        run: mv ./dist ./_site
      - name: Upload GitHub Pages artifact - ä¸Šä¼ 
        uses: actions/upload-pages-artifact@v2.0.0
  deploy:
    name: deploy - éƒ¨ç½²
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages - éƒ¨ç½²åˆ° Github page
        id: deployment
        uses: actions/deploy-pages@v2
